version: '3.7'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 "duke_ride_share:create_app()"
    environment:
      PGPASSWORD: example
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    volumes: 
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: rideshare
      POSTGRES_DB: production

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

volumes:
  dbdata: 